version: '2'

services:
  influxdb:
    restart: always
    image: influxdb:1.7.10
    #volumes:
      #- "./data/influxdb/:/var/lib/influxdb"
    environment:
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=password"
      - "INFLUXDB_DB=speedtest"
  speedtest-influxdb:
    restart: always
    # image: quadstingray/speedtest-influxdb:0.8.0
    build: .
    links:
      - "influxdb:influxdb"
    environment:
      - "INTERVAL=120"
#      - "SPEEDTEST_LIST_SERVERS=true"
  grafana:
    restart: always
    image: grafana/grafana:7.3.7
    volumes:
      - "./docker/grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3000:3000"
    links:
      - "influxdb:influxdb"
    environment:
      - "GF_SERVER_ROOT_URL=http://localhost"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"