[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/m-lab/ndt7-client-go"
  version = "0.4.1"

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "1.8.3"
